# Test
version: '2.4'

services:
  postgres:
    image: postgres:10
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "typeormtest"
      POSTGRES_PASSWORD: "password"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
